default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: facebook_dev
  username: facebook_dev
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: facebook_test
  username: facebook_dev
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: facebook_production
  username: facebook_admin
  password: <%= ENV['ODIN-FACEBOOK_DATABASE_PASSWORD'] %>

container:
  <<: *default
  database: facebook_container
  username: postgres
  password:
  host: db
